---
- name: Common configuration for all hosts.
  hosts: all
  sudo: yes
  roles:
  - common

- name: Common configuration for all hosts.
  hosts: broker*
  sudo: yes
  roles:
  - broker

- name: Common configuration for all hosts.
  hosts: celery*
  sudo: yes
  roles:
  - celery

- name: Common configuration for all hosts.
  hosts: node*
  sudo: yes
  roles:
  - node